name: CI Pipeline
on: [push]  # Runs on every code push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Check out your code
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: python -m pytest test_all_models.py